<script setup lang="ts">
import type { VImg } from 'vuetify/components'

withDefaults(defineProps<{
  showSubtitle?: boolean
  width?: string | number

}>(), {
  showSubtitle: false,
  width: 120,
})

const mainImg = useTemplateRef<VImg>('mainImg')
</script>

<template>
  <div class="jk-game-logo--container d-flex justify-center">
    <div>
      <v-img ref="mainImg" class="jk-game-logo" :class="{ 'pb-4': showSubtitle }" src="/logo.png" :width="width" aspect-ratio="1.81" />
      <div
        v-if="showSubtitle && mainImg?.state === 'loaded'" class="jk-game-logo--subtitle text-end text-h5 font-weight-bold mt-n7 mr-n3"
      >
        Das Spiel
      </div>
    </div>
  </div>
</template>

<style lang="scss">
.jk-game-logo {
    view-transition-name: article-thumb;

  &--subtitle {
    text-shadow: -2px 2px #000; animation:text-focus-in 1s cubic-bezier(.55,.085,.68,.53) both
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2024-6-9 10:58:29
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

 @keyframes text-focus-in{0%{filter:blur(12px);opacity:0}100%{filter:blur(0);opacity:1}}
</style>
