<script setup lang="ts">
const emits = defineEmits<{
  showResults: []
}>()

const showOverlay = ref(false)
setTimeout(() => showOverlay.value = true, 1500)
</script>

<template>
  <div v-if="showOverlay" class="hero-fallen flex-column d-flex align-center justify-center">
    <div class="text-center">
      <span class="hero-fallen--text font-weight-bold text-h1">
        Dein Held ist gefallen!
      </span>
    </div>
    <v-btn size="x-large" class="mt-3" color="primary" @click="emits('showResults')">
      Resultat anzeigen
    </v-btn>
  </div>
</template>

<style lang="scss" scoped>
.hero-fallen {
  position: absolute;
  top: 0;
  left: 0;
  height: 100%;
  width: 100%;
  background: rgba(183, 183, 183, 0.7);
  color: #000;

  &--text {
    text-shadow: rgb(255, 255, 255) 3px 3px 0px;
    animation: focus-in-expand-fwd 0.8s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
  }
}

/* ----------------------------------------------
 * Generated by Animista on 2025-5-30 20:15:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation focus-in-expand-fwd
 * ----------------------------------------
 */
@keyframes focus-in-expand-fwd {
  0% {
    letter-spacing: -0.5em;
    transform: translateZ(-800px);
    filter: blur(12px);
    opacity: 0;
  }

  100% {
    transform: translateZ(0);
    filter: blur(0);
    opacity: 1;
  }
}
</style>
